FROM ruby:2.7.0
RUN apt-get update -qq \
&& apt-get install -y nodejs sqlite3
#RUN npm install -g yarn@1

WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install
COPY . /app

EXPOSE 3000

RUN bundle
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]