version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    command: bash -c "bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    depends_on:
      - nginx
  nginx:
    build:
      context: .
      dockerfile: ./docker/web/nginx.DockerFile
    depends_on:
      - app
    ports:
      - 80:80