version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./app/DockerFile
    command: bash -c "bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    depends_on:
      - postgres
  nginx:
    build:
      context: .
      dockerfile: ./web/nginx.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80