version: '3.8'

services:
  app: 
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
  
  web:
    build:
      context: .
      dockerfile: ./docker/web/DockerFile
    depends_on: 
      - app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      volumes:
       - .:/Rails-Docker
    ports:
      - "80:3000"
